services:
  product-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"